---
title: "Big Data Bowl 2023 Results Table"
author: 'Connor Nickol and Josh Gen, email: can2hr@virginia.edu'
date: "2023-01-05"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
runtime: shiny    
---

```{r setup, include=FALSE,warning=FALSE,echo=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
library(shiny)
library(shinythemes)
```


```{r,include=FALSE,warning=FALSE,message=FALSE}
## Looking at Speed
speed_coef <- read_csv('speed_coeff.csv')
logos <- read_csv('logos.csv')
pics <- read_csv('linemanlinks.csv')

speed_coef$mean_scaled <- scale(speed_coef$mean)[,1]

speed_coef_filt <- speed_coef %>% left_join(logos) %>% left_join(pics, by = c('tackle_name' = 'Player')) %>% select(link_to_pic, tackle_name, link,team, mean_scaled, sd, n) %>% filter(n >= 5) %>% mutate(mean_scaled = round(mean_scaled, 3),sd = round(sd,3),Ranking = rank(-mean_scaled, ties.method = 'first')) %>% 
  rename(`Speed Score` = mean_scaled, `Speed Score SD` = sd, `Number of Speed Rushes Faced` = n, ` ` = link, Player = tackle_name, Team = team, `  ` = link_to_pic)

```

```{r,include=FALSE,warning=FALSE,message=FALSE}
## Looking at Power
power_coef <- read_csv("power_coeff.csv")

power_coef$mean_scaled <- scale(power_coef$mean)[,1]
power_coef_filt <- power_coef %>% left_join(logos) %>% left_join(pics, by = c('tackle_name' = 'Player')) %>% select(link_to_pic, tackle_name, link,team, mean_scaled, sd, n) %>% filter(n >= 5) %>% mutate(mean_scaled = round(mean_scaled, 3),sd = round(sd,3),Ranking = rank(-mean_scaled, ties.method = 'first')) %>% 
  rename(`Power Score` = mean_scaled, `Power Score SD` = sd, `Number of Power Rushes Faced` = n, ` ` = link, Player = tackle_name, Team = team, `  ` = link_to_pic)

```


```{r,include=FALSE,warning=FALSE,message=FALSE}
## Looking at full rankings
power_coef_full <- power_coef %>% select(tackle_name,team,mean_scaled,n) %>% 
  rename(power_mean_scaled = mean_scaled, num_power = n)

speed_coef_full <- speed_coef %>% select(tackle_name,team,mean_scaled,n) %>% 
  rename(speed_mean_scaled = mean_scaled, num_speed = n)

full_data <- full_join(power_coef_full, speed_coef_full, by=c("tackle_name", "team")) %>% na.omit()

full_data2 <- full_data %>% mutate(equal_weight = round((power_mean_scaled + speed_mean_scaled)/2,3),percent_weight = round(((power_mean_scaled)*.79 + (speed_mean_scaled)*.21)/2,3)) %>% select(-c(power_mean_scaled,speed_mean_scaled))

full_data3 <- full_data2 %>% mutate(rushes_faced = num_power+num_speed) %>% 
  filter(rushes_faced >= 10) %>% mutate(equal_rank = rank(-equal_weight,ties.method = 'first'),
                                  percent_rank = rank(-percent_weight, ties.method = 'first'))
                                  

full_data4 <- full_data3 %>% left_join(logos) %>% left_join(pics, by = c('tackle_name' = 'Player'))

full_data4 <- full_data4 %>% select(link_to_pic, tackle_name, link, team,
                                    equal_weight, equal_rank, 
                                    percent_weight, percent_rank,
                                    rushes_faced)

full_data4 <- full_data4 %>% rename(Player = tackle_name, `            ` = link, Team = team,
                                    `Total Rushes Faced` = rushes_faced, 
                                    `Score (Equal Weight S:P)` = equal_weight,
                                    `Equal Weight Ranking` = equal_rank, 
                                    `Score (Weighted by S:P Ratio)` = percent_weight,
                                    `Ratio Ranking` = percent_rank,
                                    `  ` = link_to_pic)

```

```{r,include=FALSE,warning=FALSE,message=FALSE}
starters_full_data <- full_data2 %>% mutate(rushes_faced = num_power+num_speed) %>% 
  filter(rushes_faced > 48) %>% left_join(pics, by = c('tackle_name' = 'Player')) %>% 
  mutate(equal_rank = rank(-equal_weight,ties.method = 'first'),
         percent_rank = rank(-percent_weight, ties.method = 'first'))%>% left_join(logos) %>% select(link_to_pic, tackle_name, link, team,equal_weight, equal_rank, percent_weight, percent_rank, rushes_faced) %>% rename(Player = tackle_name, ` ` = link, Team = team,
                                    `Total Rushes Faced` = rushes_faced, 
                                    `Score (Equal Weight S:P)` = equal_weight,
                                    `Equal Weight Ranking` = equal_rank, 
                                    `Score (Weighted by S:P Ratio)` = percent_weight,
                                    `Ratio Ranking` = percent_rank,
                                    `  ` = link_to_pic)

starters_power_data <- power_coef %>% left_join(logos) %>% left_join(pics, by = c('tackle_name' = 'Player')) %>% select(link_to_pic,tackle_name, link,team, mean_scaled, sd, n) %>% filter(n > 33) %>%  mutate(mean_scaled = round(mean_scaled, 3),sd = round(sd,3),Ranking = rank(-mean_scaled, ties.method = 'first')) %>% 
  rename(`Power Score` = mean_scaled, `Power Score SD` = sd, `Number of Power Rushes Faced` = n, ` ` = link, Player = tackle_name, Team = team,`  ` = link_to_pic) 

starters_speed_data <- speed_coef %>% left_join(logos) %>% left_join(pics, by = c('tackle_name' = 'Player')) %>% select(link_to_pic,tackle_name, link,team, mean_scaled, sd, n) %>% filter(n > 13) %>% mutate(mean_scaled = round(mean_scaled, 3),sd = round(sd,3),Ranking = rank(-mean_scaled, ties.method = 'first')) %>% 
  rename(`Speed Score` = mean_scaled, `Speed Score SD` = sd, `Number of Speed Rushes Faced` = n, ` ` = link, Player = tackle_name, Team = team, `  ` = link_to_pic)
```


```{r,echo=FALSE,warning=FALSE}
## Colour and values for table colour formatting
breaks <- seq(-3, 2.3, by = .25)
colors <- colorRampPalette(c("#E84B4B", "#68C949"))(length(breaks) + 1)
breaks_n <- seq(0, 129, by = 3)
colors_n <- colorRampPalette(c("#E84B4B", "#68C949"))(length(breaks_n) + 1)
breaks_speed <- seq(0, 57, by = 3)
colors_speed <- colorRampPalette(c("#E84B4B", "#68C949"))(length(breaks_speed) + 1)

ui <- navbarPage(title = "Modeling Results", theme = shinytheme("spacelab"),
               checkboxInput("starters",label='"Starters" Only',value=FALSE),
      tabPanel("Full Rankings", DT::dataTableOutput("full_table")),
      tabPanel("Speed Only", DT::dataTableOutput("speed_table")),
      tabPanel("Power Only", DT::dataTableOutput("power_table"))
      )



server = function(input, output){
      output$full_table <-DT::renderDT({
        if (input$starters){
        datatable(starters_full_data,
          options = list(scrollX = TRUE,
                         scrollY = TRUE,
                         server = FALSE,
                         pageLength = 100,
                         columnDefs = list(list(className = 'dt-center',width = '100px',targets = '_all'))),
          escape = FALSE,
          filter = 'top',
          rownames = FALSE) %>% 
        formatStyle(columns = c('Player', 'Team', 'Total Rushes Faced', 'Equal Weight Ranking',
                                'Ratio Ranking'), fontWeight = 'bold') %>% 
      formatStyle(c('Score (Equal Weight S:P)', 'Score (Weighted by S:P Ratio)'), backgroundColor = styleInterval(breaks, colors), color = 'white',fontWeight = 'bold' ) %>% 
      formatStyle(c('Total Rushes Faced'), backgroundColor = styleInterval(breaks_n, colors_n), color = 'white',fontWeight = 'bold' )}
      else{
      datatable(full_data4,
          options = list(scrollX = TRUE,
                         scrollY = TRUE,
                         server = FALSE,
                         pageLength = 100,
                         columnDefs = list(list(className = 'dt-center',width = '100px',targets = '_all'))),
          escape = FALSE,
          filter = 'top',
          rownames = FALSE) %>% 
        formatStyle(columns = c('Player', 'Team', 'Total Rushes Faced', 'Equal Weight Ranking',
                                'Ratio Ranking'), fontWeight = 'bold') %>% 
      formatStyle(c('Score (Equal Weight S:P)', 'Score (Weighted by S:P Ratio)'), backgroundColor = styleInterval(breaks, colors), color = 'white',fontWeight = 'bold' ) %>% 
      formatStyle(c('Total Rushes Faced'), backgroundColor = styleInterval(breaks_n, colors_n), color = 'white',fontWeight = 'bold' )
      }
        })
      
      output$speed_table <-DT::renderDT({
        if (input$starters){
        datatable(starters_speed_data,
          options = list(scrollX = TRUE,
                         scrollY = TRUE,
                         server = FALSE,
                         pageLength = 100,
                         columnDefs = list(list(className = 'dt-center',width = '100px',targets = '_all'))),
          escape = FALSE,
          filter = 'top',
          rownames = FALSE) %>% 
        formatStyle(columns = c('Player', 'Team', 'Number of Speed Rushes Faced', 
                                'Ranking', 'Speed Score SD'), fontWeight = 'bold') %>% 
      formatStyle(c('Speed Score'), backgroundColor = styleInterval(breaks, colors),
                  color = 'white',fontWeight = 'bold' ) %>% 
      formatStyle(c('Number of Speed Rushes Faced'), backgroundColor = styleInterval(breaks_speed, colors_speed), color = 'white',fontWeight = 'bold')
          }
      else{
      datatable(speed_coef_filt,
          options = list(scrollX = TRUE,
                         scrollY = TRUE,
                         server = FALSE,
                         pageLength = 100,
                         columnDefs = list(list(className = 'dt-center',width = '100px',targets = '_all'))),
          escape = FALSE,
          filter = 'top',
          rownames = FALSE) %>% 
        formatStyle(columns = c('Player', 'Team', 'Number of Speed Rushes Faced', 
                                'Ranking', 'Speed Score SD'), fontWeight = 'bold') %>% 
      formatStyle(c('Speed Score'), backgroundColor = styleInterval(breaks, colors),
                  color = 'white',fontWeight = 'bold' ) %>% 
      formatStyle(c('Number of Speed Rushes Faced'), backgroundColor = styleInterval(breaks_speed, colors_speed), color = 'white',fontWeight = 'bold')
      }
        })
      output$power_table <-DT::renderDT({
        if (input$starters){
        datatable(starters_power_data,
          options = list(scrollX = TRUE,
                         scrollY = TRUE,
                         server = FALSE,
                         pageLength = 100,
                         columnDefs = list(list(className = 'dt-center',width = '100px',targets = '_all'))),
          escape = FALSE,
          filter = 'top',
          rownames = FALSE) %>% 
        formatStyle(columns = c('Player', 'Team', 'Number of Power Rushes Faced', 
                                'Ranking', 'Power Score SD'), fontWeight = 'bold') %>% 
      formatStyle(c('Power Score'), backgroundColor = styleInterval(breaks, colors),
                  color = 'white',fontWeight = 'bold' )%>% 
      formatStyle(c('Number of Power Rushes Faced'), backgroundColor = styleInterval(breaks_n, colors_n), color = 'white',fontWeight = 'bold')
          }
      else{
      datatable(power_coef_filt,
          options = list(scrollX = TRUE,
                         scrollY = TRUE,
                         server = FALSE,
                         pageLength = 100,
                         columnDefs = list(list(className = 'dt-center',width = '100px',targets = '_all'))),
          escape = FALSE,
          filter = 'top',
          rownames = FALSE) %>% 
        formatStyle(columns = c('Player', 'Team', 'Number of Power Rushes Faced', 
                                'Ranking', 'Power Score SD'), fontWeight = 'bold') %>% 
      formatStyle(c('Power Score'), backgroundColor = styleInterval(breaks, colors),
                  color = 'white',fontWeight = 'bold' )%>% 
      formatStyle(c('Number of Power Rushes Faced'), backgroundColor = styleInterval(breaks_n, colors_n), color = 'white',fontWeight = 'bold')
      }
        })
  }

shinyApp(ui = ui, server = server, options = list(height = 1000))
```


